---
on:
  pull_request:
    branches:
      - main

name: Commit lint
jobs:
  lint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@v4.3.0
    with:
      runs-on: ubuntu-latest
      release-enabled: false
      lint-enabled: true